// app/layout.js
import './globals.css'
import Navbar from '../components/Navbar'
import ImageSlider from '@/components/ImageSlider';
import IntroSection from '@/components/IntroSection';
import Services from '@/components/Services';
import WhyWork from '@/components/WhyWork';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Navbar />
        <ImageSlider/>
        <IntroSection />
        <Services/>
        <WhyWork />
        <main>{children}</main>
      </body>
    </html>
  );
}
